#!/usr/bin/env python
# _*_ coding:utf-8 _*_

# 楦属性定义 数组
LASTATTRIBUTES = [     'basicsize',
                       'brand',
                       'shoetype',
                       'fattype',
                       'footaround',
                       'footbackarcdistance54mm',
                       'footbackarcdistancemouth',
                       'footbackbodylength',
                       'footbackfacedistance',
                       'footbackgirth',
                       'footbasicwidth',
                       'footbitfingeroutsidewidth',
                       'footboatcurveheight',
                       'footbottomheartconcavity',
                       'footdegreerejection',
                       'footfifthtoeoutsidewidth',
                       'footfirstplantarjointheight',
                       'footfirsttoeinsidewidth',
                       'footforepalmconvexity',
                       'footfrontcross',
                       'footheadthickness',
                       'footheelbulgeheight',
                       'footheelheartconvexity',
                       'footheelheartwidth',
                       'footheelheight',
                       'footlandspot',
                       'footmetatarsalgirth',
                       'footmouthbackheight',
                       'footmouthgirth',
                       'footmouthlength',
                       'footmouthwidth',
                       'footpalmwidth',
                       'footpocketheelgirth',
                       'footshoelastcalculatelength',
                       'footstruct',
                       'foottarsalboneheight',
                       'foottarsalgirth',
                       'footthumbinsidewidth',
                       'footwaistgirth',
                       'footwaistwidth',
                       'footwidth',
                       'gender',
                       'headform',
                       'shoelastbaseno',
                       'shoepadthicknessforefoot',
                       'shoepadthicknessheel']
# 楦属性字符串
LASTATTRIBUTESSTR = ','.join(LASTATTRIBUTES)