#!/usr/bin/env python
# _*_ coding:utf-8 _*_

# 脚 楦  属性 变量定义

# 脚属性定义  数组
FOOTATTRIBUTES = ['foot_length_original_left',
     'foot_length_original_right',
     'foot_length_left',
     'foot_length_right',
     'first_metatarsophalangeal_convex_length_left',
     'first_metatarsophalangeal_convex_length_right',
     'fifth_metatarsophalangeal_convex_length_left',
     'fifth_metatarsophalangeal_convex_length_right',
     'first_metatarsophalangeal_joint_length_left',
     'first_metatarsophalangeal_joint_length_right',
     'fifth_metatarsophalangeal_joint_length_left',
     'fifth_metatarsophalangeal_joint_length_right',
     'tarsal_bone_length_left',
     'tarsal_bone_length_right',
     'waist_length_left',
     'waist_length_right',
     'heel_heart_length_left',
     'heel_heart_length_right',
     'waist_girth_length_left',
     'waist_girth_length_right',
     'back_girth_length_left',
     'back_girth_length_right',
     'metatarsophalangeal_length_left',
     'metatarsophalangeal_length_right',
     'heel_up_edge_distance_left',
     'heel_up_edge_distance_right',
     'first_metatarsophalangeal_convex_width_left',
     'first_metatarsophalangeal_convex_width_right',
     'fifth_metatarsophalangeal_convex_width_left',
     'fifth_metatarsophalangeal_convex_width_right',
     'first_metatarsophalangeal_joint_width_left',
     'first_metatarsophalangeal_joint_width_right',
     'fifth_metatarsophalangeal_joint_width_left',
     'fifth_metatarsophalangeal_joint_width_right',
     'base_width_left',
     'base_width_right',
     'metatarsophalangeal_width_left',
     'metatarsophalangeal_width_right',
     'waist_width_left',
     'waist_width_right',
     'heel_heart_width_left',
     'heel_heart_width_right',
     'first_metatarsophalangeal_convex_footprint_width_left',
     'first_metatarsophalangeal_convex_footprint_width_right',
     'fifth_metatarsophalangeal_convex_footprint_width_left',
     'fifth_metatarsophalangeal_convex_footprint_width_right',
     'first_metatarsophalangeal_joint_footprint_width_left',
     'first_metatarsophalangeal_joint_footprint_width_right',
     'fifth_metatarsophalangeal_joint_footprint_width_left',
     'fifth_metatarsophalangeal_joint_footprint_width_right',
     'waist_footprint_width_left',
     'waist_footprint_width_right',
     'first_metatarsophalangeal_convex_edge_width_left',
     'first_metatarsophalangeal_convex_edge_width_right',
     'fifth_metatarsophalangeal_convex_edge_width_left',
     'fifth_metatarsophalangeal_convex_edge_width_right',
     'first_metatarsophalangeal_joint_edge_width_left',
     'first_metatarsophalangeal_joint_edge_width_right',
     'fifth_metatarsophalangeal_joint_edge_width_left',
     'fifth_metatarsophalangeal_joint_edge_width_right',
     'waist_edge_width_left',
     'waist_edge_width_right',
     'heel_heart_inside_edge_width_left',
     'heel_heart_inside_edge_width_right',
     'heel_heart_outside_edge_width_left',
     'heel_heart_outside_edge_width_right',
     'foot_arch_param_left',
     'foot_arch_param_right',
     'thumb_top_height_left',
     'thumb_top_height_right',
     'first_metatarsophalangeal_joint_height_left',
     'first_metatarsophalangeal_joint_height_right',
     'tarsal_bone_height_left',
     'tarsal_bone_height_right',
     'lateral_malleolus_height_left',
     'lateral_malleolus_height_right',
     'metatarsophalangeal_girth_left',
     'metatarsophalangeal_girth_right',
     'plantar_girth_left',
     'plantar_girth_right',
     'waist_girth_left',
     'waist_girth_right',
     'tarsal_girth_left',
     'tarsal_girth_right',
     'back_girth_left',
     'back_girth_right',
     'pocket_heel_girth_left',
     'pocket_heel_girth_right',
     'ankle_girth_left',
     'ankle_girth_right',
     'calf_height_left',
     'calf_height_right',
     'below_knee_height_left',
     'below_knee_height_right',
     'calf_girth_left',
     'calf_girth_right',
     'below_knee_girth_left',
     'below_knee_girth_right',
     'arch_top_height_left',
     'arch_top_height_right',
     'arch_top_width_left',
     'arch_top_width_right',
     'heel_inside_convex_length_left',
     'heel_inside_convex_length_right',
     'heel_outside_convex_length_left',
     'heel_outside_convex_length_right',
     'heel_convex_width_left',
     'heel_convex_width_right',
     'heel_inside_convex_width_left',
     'heel_inside_convex_width_right',
     'heel_outside_convex_width_left',
     'heel_outside_convex_width_right',
     'heel_gap_left',
     'heel_gap_right',
     'heel_gap_tolerance_left',
     'heel_gap_tolerance_right',
     'heel_inside_convex_edge_width_left',
     'heel_inside_convex_edge_width_right',
     'heel_outside_convex_edge_width_left',
     'heel_outside_convex_edge_width_right',
     'boat_curve_height_left',
     'boat_curve_height_right',
     'ankle_height_left',
     'ankle_height_right',
     'kyphosis_height_left',
     'kyphosis_height_right',
     'back_arch_gap_54_left',
     'back_arch_gap_54_right',
     'back_arch_gap_70_left',
     'back_arch_gap_70_right',
     'back_arch_gap_85_left',
     'back_arch_gap_85_right',
     'back_arch_gap_90_left',
     'back_arch_gap_90_right',
     'angle_between_heel_line_and_axis_line_left',
     'angle_between_heel_line_and_axis_line_right',
     'foot_inoutside_turn_left',
     'foot_inoutside_turn_right',
     'foot_inoutside_rotate_left',
     'foot_inoutside_rotate_right',
     'first_metatarsophalangeal_length_left',
     'first_metatarsophalangeal_length_right',
     'second_metatarsophalangeal_length_left',
     'second_metatarsophalangeal_length_right',
     'third_metatarsophalangeal_length_left',
     'third_metatarsophalangeal_length_right',
     'shoe_type_left',
     'shoe_type_right']


# 脚数据部分字段范围定义
FOOTATTRIBUTES_RULES = {'base_width_left': [75, 115],
              'heel_heart_width_left': [52, 80],
              'thumb_top_height_left': [12, 30],
              'first_metatarsophalangeal_joint_height_left': [30, 60],
              'tarsal_bone_height_left': [36, 72],
              'plantar_girth_left': [190, 270],
              'tarsal_girth_left': [190, 290],
              'pocket_heel_girth_left': [255, 380],
              'metatarsophalangeal_width_left': [50, 99],
              'metatarsophalangeal_girth_left': [130, 230],
              'foot_length_original_left': [170, 300],
              'base_width_right': [75, 115],
              'heel_heart_width_right': [52, 80],
              'thumb_top_height_right': [12, 30],
              'first_metatarsophalangeal_joint_height_right': [30, 60],
              'tarsal_bone_height_right': [36, 72],
              'plantar_girth_right': [190, 270],
              'tarsal_girth_right': [190, 290],
              'pocket_heel_girth_right': [255, 380],
              'metatarsophalangeal_width_right': [50, 99],
              'metatarsophalangeal_girth_right': [130, 230],
              'foot_length_original_right': [170, 300],
              }